sql:
  user: 'user'
  password: 'password'
  jdbcUrl: 'jdbc:mariadb://127.0.0.1:3306/blockprotection?useSSL=false'
  driverClassName: 'org.mariadb.jdbc.Driver'
  poolSize: 10
protection:
  protected_worlds:
    - world
  protected_blocks:
    - OAK_LOG
    - OAK_WOOD
    - STRIPPED_OAK_LOG
    - STRIPPED_OAK_WOOD
    - OAK_PLANKS
    - OAK_STAIRS
    - OAK_SLAB
    - OAK_FENCE
    - OAK_FENCE_GATE
    - SPRUCE_PLANKS
    - STRIPPED_SPRUCE_WOOD
    - STRIPPED_SPRUCE_LOG
    - SPRUCE_WOOD
    - SPRUCE_LOG
    - SPRUCE_STAIRS
    - SPRUCE_SLAB
    - SPRUCE_FENCE
    - SPRUCE_FENCE_GATE
    - BIRCH_LOG
    - BIRCH_FENCE_GATE
    - BIRCH_FENCE
    - BIRCH_SLAB
    - BIRCH_STAIRS
    - BIRCH_PLANKS
    - STRIPPED_BIRCH_WOOD
    - STRIPPED_BIRCH_LOG
    - BIRCH_WOOD
    - JUNGLE_LOG
    - JUNGLE_WOOD
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_JUNGLE_WOOD
    - JUNGLE_PLANKS
    - JUNGLE_STAIRS
    - JUNGLE_SLAB
    - JUNGLE_FENCE
    - JUNGLE_FENCE_GATE
    - ACACIA_LOG
    - ACACIA_WOOD
    - ACACIA_FENCE
    - ACACIA_FENCE_GATE
    - ACACIA_SLAB
    - ACACIA_STAIRS
    - ACACIA_PLANKS
    - STRIPPED_ACACIA_WOOD
    - STRIPPED_ACACIA_LOG
    - DARK_OAK_LOG
    - DARK_OAK_WOOD
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_DARK_OAK_WOOD
    - DARK_OAK_PLANKS
    - DARK_OAK_SLAB
    - DARK_OAK_FENCE
    - MANGROVE_LOG
    - MANGROVE_WOOD
    - STRIPPED_MANGROVE_LOG
    - MANGROVE_LOG
    - MANGROVE_WOOD
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_MANGROVE_WOOD
    - MANGROVE_PLANKS
    - MANGROVE_STAIRS
    - MANGROVE_SLAB
    - MANGROVE_FENCE
    - MANGROVE_FENCE_GATE
    - CRIMSON_STEM
    - CRIMSON_HYPHAE
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_CRIMSON_HYPHAE
    - CRIMSON_PLANKS
    - CRIMSON_STAIRS
    - CRIMSON_SLAB
    - CRIMSON_FENCE
    - CRIMSON_FENCE_GATE
    - WARPED_STEM
    - WARPED_HYPHAE
    - STRIPPED_WARPED_STEM
    - STRIPPED_WARPED_HYPHAE
    - WARPED_PLANKS
    - WARPED_STAIRS
    - WARPED_SLAB
    - WARPED_FENCE
    - WARPED_FENCE_GATE
    - STONE
    - STONE_STAIRS
    - STONE_SLAB
    - COBBLESTONE
    - COBBLESTONE_SLAB
    - COBBLESTONE_STAIRS
    - COBBLESTONE_WALL
    - MOSSY_COBBLESTONE
    - MOSSY_COBBLESTONE_STAIRS
    - MOSSY_COBBLESTONE_SLAB
    - MOSSY_COBBLESTONE_WALL
    - SMOOTH_STONE
    - STONE_BRICKS
    - CRACKED_STONE_BRICKS
    - STONE_BRICK_STAIRS
    - STONE_BRICK_SLAB
    - STONE_BRICK_WALL
    - CHISELED_STONE_BRICKS
    - MOSSY_STONE_BRICKS
    - MOSSY_STONE_BRICK_STAIRS
    - MOSSY_STONE_BRICK_SLAB
    - GRANITE
    - GRANITE_SLAB
    - GRANITE_WALL
    - POLISHED_GRANITE
    - DIORITE
    - DIORITE_SLAB
    - POLISHED_DIORITE
    - POLISHED_DIORITE_SLAB
    - ANDESITE
    - ANDESITE_STAIRS
    - ANDESITE_WALL
    - POLISHED_ANDESITE_STAIRS
    - POLISHED_ANDESITE_SLAB
    - COBBLED_DEEPSLATE
    - COBBLED_DEEPSLATE_SLAB
    - CHISELED_DEEPSLATE
    - POLISHED_DEEPSLATE_STAIRS
    - POLISHED_DEEPSLATE_SLAB
    - POLISHED_DEEPSLATE_WALL
    - DEEPSLATE_BRICKS
    - CRACKED_DEEPSLATE_BRICKS
    - DEEPSLATE_BRICK_STAIRS
    - DEEPSLATE_BRICK_SLAB
    - DEEPSLATE_BRICK_WALL
    - DEEPSLATE_TILES
    - CRACKED_DEEPSLATE_TILES
    - POLISHED_DEEPSLATE
    - COBBLED_DEEPSLATE_SLAB
    - COBBLED_DEEPSLATE
    - DEEPSLATE_TILE_STAIRS
    - DEEPSLATE_TILE_SLAB
    - REINFORCED_DEEPSLATE
    - BRICK_STAIRS
    - BRICK_WALL
    - PACKED_MUD
    - CHISELED_SANDSTONE
    - SANDSTONE_SLAB
    - MUD_BRICK_WALL
    - MUD_BRICK_STAIRS
    - SMOOTH_SANDSTONE
    - SMOOTH_SANDSTONE_STAIRS
    - SMOOTH_SANDSTONE_SLAB
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - RED_SANDSTONE
    - RED_SANDSTONE_STAIRS
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_WALL
    - PRISMARINE_STAIRS
    - PRISMARINE
    - CUT_RED_SANDSTONE_SLAB
    - CUT_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE_SLAB
    - SMOOTH_RED_SANDSTONE_STAIRS
    - SMOOTH_RED_SANDSTONE
    - PRISMARINE_SLAB
    - PRISMARINE_WALL
    - PRISMARINE_BRICK_STAIRS
    - DARK_PRISMARINE
    - DARK_PRISMARINE_SLAB
    - RED_NETHER_BRICK_STAIRS
    - CHISELED_NETHER_BRICKS
    - NETHER_BRICK_WALL
    - NETHER_BRICK_SLAB
    - CRACKED_NETHER_BRICKS
    - POLISHED_BLACKSTONE_BRICKS
    - BLACKSTONE_SLAB
    - BLACKSTONE_STAIRS
    - GILDED_BLACKSTONE
    - BLACKSTONE
    - POLISHED_BLACKSTONE_WALL
    - POLISHED_BLACKSTONE_SLAB
    - POLISHED_BASALT
    - SMOOTH_BASALT
    - POLISHED_BLACKSTONE_STAIRS
    - BASALT
    - RED_NETHER_BRICK_WALL
    - BLACKSTONE_WALL
    - CRACKED_POLISHED_BLACKSTONE_BRICKS
    - POLISHED_BLACKSTONE_BRICK_SLAB
    - END_STONE
    - END_STONE_BRICK_STAIRS
    - END_STONE_BRICK_WALL
    - IRON_BLOCK
    - COAL_BLOCK
    - PURPUR_STAIRS
    - PURPUR_BLOCK
    - IRON_BLOCK
    - GOLD_BLOCK
    - REDSTONE_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - DIAMOND_BLOCK
    - NETHERITE_BLOCK
    - SMOOTH_QUARTZ_SLAB
    - SMOOTH_QUARTZ_STAIRS
    - SMOOTH_QUARTZ
    - QUARTZ_PILLAR
    - QUARTZ_BRICKS
    - CHISELED_QUARTZ_BLOCK
    - QUARTZ_SLAB
    - QUARTZ_BLOCK
    - COPPER_BLOCK
    - CUT_COPPER_STAIRS
    - CUT_COPPER_SLAB
    - EXPOSED_CUT_COPPER
    - EXPOSED_CUT_COPPER_SLAB
    - OXIDIZED_CUT_COPPER_SLAB
    - OXIDIZED_CUT_COPPER
    - WEATHERED_CUT_COPPER_SLAB
    - WEATHERED_CUT_COPPER_STAIRS
    - WEATHERED_COPPER
    - WAXED_OXIDIZED_CUT_COPPER_SLAB
    - WAXED_OXIDIZED_CUT_COPPER_STAIRS
    - WAXED_EXPOSED_CUT_COPPER
    - WAXED_EXPOSED_CUT_COPPER_SLAB
    - WAXED_WEATHERED_CUT_COPPER
    - WAXED_EXPOSED_COPPER
    - WAXED_OXIDIZED_CUT_COPPER
    - WAXED_CUT_COPPER_SLAB
    - WAXED_CUT_COPPER_STAIRS
    - WAXED_WEATHERED_CUT_COPPER_STAIRS
    - WHITE_WOOL
    - GREEN_WOOL
    - CYAN_WOOL
    - LIGHT_GRAY_WOOL
    - LIGHT_BLUE_WOOL
    - BLACK_WOOL
    - PURPLE_WOOL
    - RED_WOOL
    - PINK_WOOL
    - YELLOW_WOOL
    - GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - WHITE_TERRACOTTA
    - GREEN_TERRACOTTA
    - TERRACOTTA
    - ORANGE_TERRACOTTA
    - BROWN_TERRACOTTA
    - BLACK_TERRACOTTA
    - BROWN_CONCRETE
    - PURPLE_CONCRETE
    - ORANGE_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - BLUE_CONCRETE
    - BLACK_CONCRETE
    - LIGHT_BLUE_CONCRETE
    - PURPLE_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE
    - WHITE_CONCRETE
    - GRAY_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - LIME_CONCRETE
    - MAGENTA_TERRACOTTA
    - WHITE_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - ORANGE_CONCRETE
    - BLUE_TERRACOTTA
    - RED_CONCRETE
    - YELLOW_CONCRETE_POWDER
    - WHITE_GLAZED_TERRACOTTA
    - GREEN_GLAZED_TERRACOTTA
    - CYAN_GLAZED_TERRACOTTA
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - GRAY_GLAZED_TERRACOTTA
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - BLACK_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
    - MAGENTA_GLAZED_TERRACOTTA
    - RED_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - LIME_STAINED_GLASS
    - YELLOW_STAINED_GLASS
    - GLASS
    - PINK_STAINED_GLASS
    - BROWN_STAINED_GLASS
    - BLUE_STAINED_GLASS
    - GRAY_STAINED_GLASS
    - CYAN_STAINED_GLASS
    - GREEN_STAINED_GLASS
    - GLASS_PANE
    - LIME_STAINED_GLASS_PANE
    - GREEN_STAINED_GLASS_PANE
    - WHITE_STAINED_GLASS_PANE
    - YELLOW_STAINED_GLASS_PANE
    - ORANGE_STAINED_GLASS_PANE
    - PINK_STAINED_GLASS_PANE
    - RED_STAINED_GLASS_PANE
    - PURPLE_STAINED_GLASS_PANE
    - BLACK_STAINED_GLASS_PANE
    - LIGHT_BLUE_STAINED_GLASS_PANE
    - LIGHT_GRAY_STAINED_GLASS_PANE
    - GRASS_BLOCK
    - PODZOL
    - MYCELIUM
    - DIRT_PATH
    - DIRT
    - COARSE_DIRT
    - ROOTED_DIRT
    - FARMLAND
    - MUD
    - RED_SANDSTONE
    - RED_SAND
    - SANDSTONE
    - CLAY
    - SNOW_BLOCK
    - MOSS_BLOCK
    - DEEPSLATE
    - DIORITE
    - NETHERRACK
    - END_STONE
    - CRYING_OBSIDIAN
    - BASALT
    - MAGMA_BLOCK
    - BONE_BLOCK
    - SOUL_SAND
    - CALCITE
    - WARPED_NYLIUM
    - REDSTONE_ORE
    - NETHER_QUARTZ_ORE
    - NETHER_GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - GOLD_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DIAMOND_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_EMERALD_ORE
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_REDSTONE_ORE
    - RAW_COPPER_BLOCK
    - GLOWSTONE
    - BUDDING_AMETHYST
    - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - NETHER_WART_BLOCK
    - WARPED_WART_BLOCK
    - SHROOMLIGHT
    - MUDDY_MANGROVE_ROOTS
    - DRIED_KELP_BLOCK
    - TUBE_CORAL_BLOCK
    - BRAIN_CORAL_BLOCK
    - BUBBLE_CORAL_BLOCK
    - FIRE_CORAL_BLOCK
    - HORN_CORAL_BLOCK
    - DEAD_HORN_CORAL_BLOCK
    - DEAD_FIRE_CORAL_BLOCK
    - DEAD_BUBBLE_CORAL_BLOCK
    - DEAD_BRAIN_CORAL_BLOCK
    - DEAD_TUBE_CORAL_BLOCK
    - OCHRE_FROGLIGHT
    - VERDANT_FROGLIGHT
    - PEARLESCENT_FROGLIGHT
    - SCULK
    - SCULK_CATALYST
    - HONEY_BLOCK
    - HONEY_BLOCK
    - SLIME_BLOCK
    - HONEYCOMB_BLOCK
    - BEE_NEST
    - HAY_BLOCK
    - SEA_LANTERN
    - REDSTONE_LAMP
    - CRAFTING_TABLE
    - MAGMA_BLOCK
    - GLOWSTONE
    - SHROOMLIGHT
    - CARTOGRAPHY_TABLE
    - FLETCHING_TABLE
    - SMITHING_TABLE
    - FURNACE
    - SMOKER
    - BLAST_FURNACE
    - JUKEBOX
    - NOTE_BLOCK
    - LODESTONE
    - LODESTONE
    - TINTED_GLASS
    - ANCIENT_DEBRIS
    - TARGET
