name: PotoCraft
version: 0.1
main: com.rafaelsms.potocraft.PotoCraftPlugin
load: STARTUP
api-version: 1.19
commands:
  allow:
    aliases: [ permitir ]
    description: Allow another player to place and break blocks nearby.
  allowlist:
    aliases: [ allowed, permitidos ]
    description: Lists which players can place and break blocks nearby.
  disallow:
    aliases: [ proibir ]
    description: Disallow another player from place and break blocks nearby.
